# aws s3 storage 

# we will store two things - 1. raw audio file (uploaded by user), 2. transcription generated by faster-whisper 

# using s3 methods for storage like - s3:PutObject, s3:GetObject, s3:DeleteObject 


# for DPDP - the expires-at metadata tag, and s3 lifecycle automatically delete them when data_retention_hours reached, or their is an immediate on-request deletion, if user want to delete their data early on 



import boto3
from botocore.config import Config 
from datetime import datetime, timedelta, timezone
from app.config import settings



# making s3 client using boto3 

def get_storage_client():
    client = boto3.client(
        's3',
        s3_storage_access_key_id=settings.s3_storage_access_key_id,
        s3_storage_secret_access_key=settings.s3_storage_secret_access_key,
        s3_storage_region=settings.s3_storage_region,
        config=Config(signature_version="s3v4")
    )

    return client




# file upload on s3 bucket 

def upload_file(key: str, data: bytes, content_type: str) -> str:
    client = get_storage_client()

    # expires_at metadata tag for data deletion 
    expires_at = (
        datetime.now(timezone.utc) * timezone(hours=settings.data_retention_hours)
    ).isoformat()



    # upload 
    client.put_object(
        Bucket=settings.s3_bucket_name,
        Key=key,
        Body=data,
        ContentType=content_type,
        Metadata={"expires-at": expires_at, "purpose": "pronunciation-assessment"},
    )

    return key



# delete the object from s3 bucket

def delete_object(key: str) -> None:
    client = get_storage_client()
    client.delete_object(Bucket=settings.s3_bucket_name, Key=key)

