# aws s3 storage 

# we will store two things - 1. raw audio file (uploaded by user), 2. transcription generated by faster-whisper 

# using s3 methods for storage like - s3:PutObject, s3:GetObject, s3:DeleteObject 

# for DPDP - the expires-at metadata tag, and s3 lifecycle automatically delete them when data_retention_hours reached, or their is an immediate on-request deletion, if user want to delete their data early on 



import boto3

from botocore.client import BaseClient
from botocore.config import Config
from botocore.exceptions import ClientError

from datetime import datetime, timedelta, timezone
from app.config import settings




# s3 client with boto3 

s3_client: BaseClient = boto3.client(
   "s3",
   aws_access_key_id=settings.s3_storage_access_key_id,
   aws_secret_access_key=settings.s3_storage_secret_access_key,
   region_name=settings.s3_storage_region,
   config=Config(signature_version="s3v4"),
)


# upload file function 


def upload_file(key: str, data: bytes, content_type: str) -> str:
  
  # expiration (object deletion) after data_retention_hours = 48hrs from first upload 

  expires_at = (
     datetime.now(timezone.utc) + timedelta(hours=settings.data_retention_hours)
  ).isoformat()


  # putting object (put_object) to the s3 client 

  try:
    s3_client.put_object(
      Bucket=settings.s3_storage_bucket_name,
      Key=key,
      Body=data,
      ContentType=content_type,
      Metadata={
        "purpose": "pronunciation-app",
        "expires_at": expires_at,
      },
      ServerSideEncryption="AES256",
    )


    return key
  

  except (ClientError, Exception) as e:
      raise RuntimeError(f"Failed to upload the object: {e}")
  



# delete the object 
  

def delete_object(key: str) -> None:
     
     try:
        s3_client.delete_object(
           Bucket=settings.s3_storage_bucket_name,
           Key=key,
        )


     except ClientError as e:
        raise RuntimeError(f"Failed to delete the object:{e}")










